[tool.poetry]
name = "aula17"
version = "0.1.0"
description = "meu projeto"
authors = ["samuel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
